data_1:
  path: C:\\data\\query_1.csv
  rename_columns: userId->user_id,productId->item_id,clicks->rating
  type: csv
data_3:
  rename_columns: userId->user_id,productId->item_id,clicks->rating
  type: api
  url: https://api.example.com/data?param=value
data_4:
  collection: collection_name
  database: database_name
  rename_columns: userId->user_id,productId->item_id,clicks->rating
  type: nosql
data_5:
  brokers: broker1:9092,broker2:9092
  group_id: data_group
  rename_columns: userId->user_id,productId->item_id,clicks->rating
  topic: data_topic
  type: messaging
data_a:
  type: sql
  query: SELECT user_id, item_id, rating FROM interactions
  rename_columns: ""
